vendas = float(input("QUAL O TOTAL DE VENDAS DO MÊS?", )) #INSERE O VALOR DAS VENDAS NO MES
Ameta = vendas * 0.05 # SE O VALOR FOR IGUAL OU MAIOR QUE A META DE 50000 PEGA OS 5% DE COMISSÃO
Bmeta = vendas * 0.03 # SE O VALOR FOR MENOR QUE A META DE 50000 PEGA OS 3% DA COMISSÃO

if vendas >= 50000 and Ameta > 3000: #SE ELE BATEU A META E SUA COMISSÃO FOI > 3000
    print("OSALRIO DO VENDEDOR É DE", Ameta + 400) #ELE RECEBERA O VALOR DA COMISSÃO + 400 REAIS DE AUXILIO

elif vendas >= 50000 and Ameta <= 3000:
    print("OSALRIO DO VENDEDOR É DE", Ameta + 750) #SE < 3000 ELE RECEBERA A COMISSÃO + 750 REAIS DE AUXILIO 

elif vendas < 50000 and Bmeta <= 3000: # SE ELE TIVER AS VENDAS A BAIXO DA META 
    print("OSALRIO DO VENDEDOR É DE", Bmeta + 750) # RECEBERA O VALOR SOBRE 3% DE COMISSÃO + 750 REAIS DE AUXILIO   